import { useEffect, useState } from 'react';
import { Actor, HttpAgent } from '@dfinity/agent';
import { useInternetIdentity } from './useInternetIdentity';

// This will be generated by dfx generate
// For now, we'll use a placeholder type
export type BackendActor = any;

const canisterId = import.meta.env.VITE_BACKEND_CANISTER_ID || 'rrkah-fqaaa-aaaaa-aaaaq-cai';

export const useActor = () => {
  const { authClient, isAuthenticated } = useInternetIdentity();
  const [actor, setActor] = useState<BackendActor | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authClient) {
      setLoading(false);
      return;
    }

    const initActor = async () => {
      try {
        const identity = authClient.getIdentity();

        const host = import.meta.env.VITE_DFX_NETWORK === 'ic'
          ? 'https://icp0.io'
          : 'http://localhost:8000';

        const agent = new HttpAgent({
          host,
          identity,
        });

        // Fetch root key for local development
        if (import.meta.env.VITE_DFX_NETWORK !== 'ic') {
          await agent.fetchRootKey();
        }

        // Create actor using the IDL interface
        // This would normally be imported from the generated declarations
        // For now, we'll create a basic actor
        const backendActor = Actor.createActor(
          ({ IDL }: any) => IDL.Service({
            // Define the canister interface here
            // This should match the backend main.mo public functions
            initializeAccessControl: IDL.Func([], [], []),
            getCallerUserRole: IDL.Func([], [IDL.Text], ['query']),
            getCallerUserProfile: IDL.Func([], [IDL.Opt(IDL.Record({
              name: IDL.Text,
              role: IDL.Variant({
                Producer: IDL.Null,
                Artist: IDL.Null,
              }),
            }))], ['query']),
            saveCallerUserProfile: IDL.Func([IDL.Record({
              name: IDL.Text,
              role: IDL.Variant({
                Producer: IDL.Null,
                Artist: IDL.Null,
              }),
            })], [], []),
            // Add more functions as needed
          }),
          {
            agent,
            canisterId,
          }
        );

        setActor(backendActor);
      } catch (error) {
        console.error('Failed to initialize actor:', error);
      } finally {
        setLoading(false);
      }
    };

    initActor();
  }, [authClient, isAuthenticated]);

  return { actor, loading };
};
